// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwbeurincdpfkzhurvne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3YmV1cmluY2RwZmt6aHVydm5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NzM4NjUsImV4cCI6MjA3MTM0OTg2NX0.X9sHzHJGhxzaC8Gw2JY4VFMdUR20-Ojq5o57bsBKtrg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});